---
- hosts: 172.31.4.169 
  become: yes
  tasks:
  - include_tasks: myfile.yml
  - name: i want to create directory
    file:
      path: /home/maha/myfolder
      state: directory

  - name:  i want to copy test file
    copy:
      src: mytestfile
      dest: /home/maha/myfolder/mytestfile
  
  - name: install apache2 
    apt:
      name: apache2
      state: present

  - name: i want to copy index file into nodes
    template:
        src: myindex.j2
        dest: /var/www/html/index.html
    notify: restartwebserver

  - name: i want to download internet(remote)  file
    get_url:
        url: https://github.com/maha4dsvc/myAnsible_DS_E_7PM_26Nov24/blob/main/installjava.yml
        dest: /home/maha/myfolder/installjava.yml
        force_basic_auth: yes


  handlers:
  - name: restartwebserver
    service:
      name: apache2
      state: restarted

   

